version: '3'
volumes:
  mysql_data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cell_shift
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
        - 'DATABASE_PASSWORD=password' 
    depends_on: 
        - db
    links:
        - db
  db:
    image: mysql:5.7
    ports:
        - '3306:3306'
    volumes:
        - 'mysql_data:/var/lib/mysql'
    environment:
        MYSQL_ROOT_PASSWORD: password
