version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          TZ: 'Asia/Tokyo'
      - image: cimg/mysql:5.5.8
        name: db
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      # set up
      - run:
          name: install gems
          command:
              bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: wait to setup db
          command: dockerize -wait tcp://db:3306 -timeout 1m
      - run:
          name: setup db
          command: bundle exec rails db:create db:schema:load
      # run test
      - run:
          name: run rspec
          command: bundle exec rspec --profile 10
      # run linter
      - run:
          name: run rubocop
          command: bundle exec rubocop

workflows:
  build:
    jobs:
      - test
